"""
gantt_ontology
==============

Scheduling parameterization plus the provenance-first Master Critical Path
domain envelope.

The legacy Gantt models remain available for backward compatibility. New MCP
truth/evidence, scholarship, syllabus, import, notification, proof, and
boundary-contract models live in ``mcp_domain`` and are additive during the
migration from the legacy single-document graph.
"""

from .models import (
    Meta,
    Project,
    Calendar,
    Resource,
    Workstream,
    Task,
    Dependency,
    Baseline,
    Boundary,
    ConfigurationProfile,
    GanttOntology,
    Duration,
    DurationUnit,
    ConstraintType,
    DependencyType,
    ResourceType,
    SchedulingMode,
    BoundaryType,
    WorkstreamType,
    InvariantItem,
    AcademicStandingItem,
    CareerMilestoneItem,
    FundingItem,
    DemographicsProfile,
)
from .mcp_domain import (
    MCPDomainEnvelope,
    AuthorityTier,
    VerificationState,
    ClaimType,
    SourceKind,
    ImpactLevel,
    ConditionOperator,
    BoundaryAction,
    NotificationSeverity,
    ImportCandidateState,
    SuggestionKind,
    SuggestionState,
    EntityRef,
    Source,
    Evidence,
    Assertion,
    RuleCondition,
    BoundaryEffect,
    BoundaryContract,
    ProofRequirement,
    CourseOffering,
    Syllabus,
    Assignment,
    EligibilityCriterion,
    RequiredDocument,
    ApplicationWindow,
    AwardFormula,
    ScholarshipProgram,
    NotificationPolicy,
    ImportArtifact,
    ImportCandidate,
    Suggestion,
)

__version__ = "1.1.0"

__all__ = [
    # Legacy scheduling ontology
    "Meta",
    "Project",
    "Calendar",
    "Resource",
    "Workstream",
    "Task",
    "Dependency",
    "Baseline",
    "Boundary",
    "ConfigurationProfile",
    "GanttOntology",
    "Duration",
    "DurationUnit",
    "ConstraintType",
    "DependencyType",
    "ResourceType",
    "SchedulingMode",
    "BoundaryType",
    "WorkstreamType",
    "InvariantItem",
    "AcademicStandingItem",
    "CareerMilestoneItem",
    "FundingItem",
    "DemographicsProfile",
    # MCP provenance-first domain
    "MCPDomainEnvelope",
    "AuthorityTier",
    "VerificationState",
    "ClaimType",
    "SourceKind",
    "ImpactLevel",
    "ConditionOperator",
    "BoundaryAction",
    "NotificationSeverity",
    "ImportCandidateState",
    "SuggestionKind",
    "SuggestionState",
    "EntityRef",
    "Source",
    "Evidence",
    "Assertion",
    "RuleCondition",
    "BoundaryEffect",
    "BoundaryContract",
    "ProofRequirement",
    "CourseOffering",
    "Syllabus",
    "Assignment",
    "EligibilityCriterion",
    "RequiredDocument",
    "ApplicationWindow",
    "AwardFormula",
    "ScholarshipProgram",
    "NotificationPolicy",
    "ImportArtifact",
    "ImportCandidate",
    "Suggestion",
]
