"""
gantt_ontology
==============

Scheduling parameterization plus the provenance-first Master Critical Path
domain envelope and deterministic evaluation services.

The legacy Gantt models remain available for backward compatibility. New MCP
truth/evidence, scholarship, syllabus, import, notification, proof, boundary
contract, ingestion, and evaluation APIs are additive during migration from the
legacy single-document graph.
"""

from .models import (
    Meta,
    Project,
    Calendar,
    Resource,
    Workstream,
    Task,
    Dependency,
    Baseline,
    Boundary,
    ConfigurationProfile,
    GanttOntology,
    Duration,
    DurationUnit,
    ConstraintType,
    DependencyType,
    ResourceType,
    SchedulingMode,
    BoundaryType,
    WorkstreamType,
    InvariantItem,
    AcademicStandingItem,
    CareerMilestoneItem,
    FundingItem,
    DemographicsProfile,
)
from .mcp_domain import (
    MCPDomainEnvelope,
    AuthorityTier,
    VerificationState,
    ClaimType,
    SourceKind,
    ImpactLevel,
    ConditionOperator,
    BoundaryAction,
    NotificationSeverity,
    ImportCandidateState,
    SuggestionKind,
    SuggestionState,
    EntityRef,
    Source,
    Evidence,
    Assertion,
    RuleCondition,
    BoundaryEffect,
    BoundaryContract,
    ProofRequirement,
    CourseOffering,
    Syllabus,
    Assignment,
    EligibilityCriterion,
    RequiredDocument,
    ApplicationWindow,
    AwardFormula,
    ScholarshipProgram,
    NotificationPolicy,
    ImportArtifact,
    ImportCandidate,
    Suggestion,
)
from .legacy_adapter import legacy_document_sha256, legacy_gantt_to_mcp_envelope
from .ingestion import (
    SyllabusAssignmentPayload,
    SyllabusImportPayload,
    ingest_syllabus_payload,
)
from .rule_engine import (
    ConditionResult,
    ContractEvaluationState,
    ConditionEvaluation,
    ProposedBoundaryEffect,
    BoundaryEvaluation,
    evaluate_boundary_contract,
    evaluate_changed_assertions,
)
from .scholarship_engine import (
    CriterionState,
    ScholarshipEligibilityState,
    CriterionEvaluation,
    ScholarshipEvaluation,
    evaluate_scholarship,
)

__version__ = "1.2.0"

__all__ = [
    # Legacy scheduling ontology
    "Meta",
    "Project",
    "Calendar",
    "Resource",
    "Workstream",
    "Task",
    "Dependency",
    "Baseline",
    "Boundary",
    "ConfigurationProfile",
    "GanttOntology",
    "Duration",
    "DurationUnit",
    "ConstraintType",
    "DependencyType",
    "ResourceType",
    "SchedulingMode",
    "BoundaryType",
    "WorkstreamType",
    "InvariantItem",
    "AcademicStandingItem",
    "CareerMilestoneItem",
    "FundingItem",
    "DemographicsProfile",
    # MCP provenance-first domain
    "MCPDomainEnvelope",
    "AuthorityTier",
    "VerificationState",
    "ClaimType",
    "SourceKind",
    "ImpactLevel",
    "ConditionOperator",
    "BoundaryAction",
    "NotificationSeverity",
    "ImportCandidateState",
    "SuggestionKind",
    "SuggestionState",
    "EntityRef",
    "Source",
    "Evidence",
    "Assertion",
    "RuleCondition",
    "BoundaryEffect",
    "BoundaryContract",
    "ProofRequirement",
    "CourseOffering",
    "Syllabus",
    "Assignment",
    "EligibilityCriterion",
    "RequiredDocument",
    "ApplicationWindow",
    "AwardFormula",
    "ScholarshipProgram",
    "NotificationPolicy",
    "ImportArtifact",
    "ImportCandidate",
    "Suggestion",
    # Adapters and ingestion
    "legacy_document_sha256",
    "legacy_gantt_to_mcp_envelope",
    "SyllabusAssignmentPayload",
    "SyllabusImportPayload",
    "ingest_syllabus_payload",
    # Boundary contract evaluation
    "ConditionResult",
    "ContractEvaluationState",
    "ConditionEvaluation",
    "ProposedBoundaryEffect",
    "BoundaryEvaluation",
    "evaluate_boundary_contract",
    "evaluate_changed_assertions",
    # Scholarship evaluation
    "CriterionState",
    "ScholarshipEligibilityState",
    "CriterionEvaluation",
    "ScholarshipEvaluation",
    "evaluate_scholarship",
]
